django/conf/project_template/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^{{ project_name }}/', include('{{ project_name }}.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # (r'^admin/', include(admin.site.urls)),
)

main/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('main.views',
    (r'^$', 'index'),
    url(r'^dance/add/$', 'dance_add'),
    url(r'^dance/(?P<id>\d+)/$', 'dance', name='dance'),
    url(r'^dance/(?P<id>\d+)/event/add/$', 'event_add'),
    url(r'^event/(?P<id>\d+)/attend/$', 'event_attend'),
    url(r'^event/(?P<id>\d+)/unattend/$', 'event_unattend'),
    url(r'^band/(?P<id>\d+)/$', 'band' ),
    url(r'^band/add/$', 'band_add'),
    url(r'^band/search/json/$', 'band_search_json'),
    url(r'^accounts/profile/(\d+)/$', 'profile'),
    url(r'^accounts/profile/$', 'home_profile' ),
    url(r'^accounts/profile/edit/$', 'profile_edit' ),
    url(r'^accounts/signup/$', 'signup', name="signup" ),
    url(r'^accounts/admin/sethome/$', 'set_home_dance',),
    url(r'^accounts/admin/unsethome/$', 'unset_home_dance'),
    url(r'^facebook_auth/$', 'facebook_auth'),
    url(r'^facebook/disconnect/$', 'facebook_disconnect'),
    url(r'^facebook/pull/$', 'facebook_pull'),

    url(r'^person/add/$', 'person_add'),
    url(r'^person/search/json/$', 'person_search_json'),

    url(r'^data/fixattendships/$', 'fixattendships'),
    url(r'^data/fixpeople/$', 'fixpeople'),
    url(r'^data/fixbands/$', 'fixbands'),
)

urls.py
from django.conf.urls.defaults import *
from django.contrib.auth.views import login

handler500 = 'djangotoolbox.errorviews.server_error'

urlpatterns = patterns('',
    (r'^accounts/login/$', 'django.contrib.auth.views.login' ), #try using django.contrib.auth.views.login instead
    (r'^accounts/logout/$', 'django.contrib.auth.views.logout_then_login' ),
    (r'^', include('main.urls')),
)

main/models.py
from django.db import models
from django.contrib.auth.models import User
from main.helpers import normalize_string

# Create your models here.

class UserProfile(models.Model):
  user = models.OneToOneField(User)
  facebook = models.OneToOneField('FacebookLink',blank=True,null=True)

  def display_name(self):
    ret = ""
    if self.user.first_name and self.user.first_name!='':
        ret = ret+self.user.first_name

    if self.user.last_name and self.user.last_name!='':
        ret = ret+" "+self.user.last_name

    if ret!='':
        return ret
    else:
        return self.user.username

class FacebookLink(models.Model):
  oauth_code = models.CharField(max_length=255)
  access_token = models.CharField(max_length=255)
  account_id = models.CharField(max_length=255)
  name = models.CharField(max_length=255)
  link = models.CharField(max_length=255)

class Person(models.Model):
  name = models.CharField(max_length=255)
  name_normalized = models.CharField(max_length=255)

  def __init__(self, *args, **kwargs):
    models.Model.__init__(self, *args, **kwargs)

    self.name_normalized = normalize_string(self.name)

  def __unicode__(self):
    return self.name

class Dance(models.Model):
  name = models.CharField(max_length=255)

  def __unicode__(self):
    return self.name

class Band(models.Model):
  name = models.CharField(max_length=255)
  name_normalized = models.CharField(max_length=255)

  def __init__(self, *args, **kwargs):
    models.Model.__init__(self, *args, **kwargs)

    self.name_normalized = normalize_string(self.name)

  def __unicode__(self):
    return self.name

class Instrument(models.Model):
  name = models.CharField(max_length=255)

class BandMember(models.Model):
  person = models.ForeignKey(Person)
  band = models.ForeignKey(Band, related_name='members')

class BandInstrument(models.Model):
  instrument = models.ForeignKey(Instrument)
  member = models.ForeignKey(BandMember, related_name='instruments')

  def __unicode__(self):
    return self.instrument.name

class Event(models.Model):
  date = models.DateField()
  dance = models.ForeignKey(Dance)
  band = models.ForeignKey(Band,null=True,blank=True)
  caller = models.ForeignKey(Person,null=True,blank=True)

  def __unicode__(self):
    return "id:%s date:%s dance_id:%s band_id:%s"%(self.id, self.date,self.dance_id,self.band_id)

class Homeship(models.Model):
  user = models.ForeignKey(User, related_name="homeships")
  dance = models.ForeignKey(Dance)

class Attendship(models.Model):
  user = models.ForeignKey(User, related_name="attendships")
  event = models.ForeignKey(Event, related_name="attendships")

  date = models.DateField(null=True) # a copy of event.date, so we can sort eventships

  def __unicode__(self):
    return "user_id:%s event_id:%s"%(self.user_id, self.event_id)

main/forms.py
from django import forms
from django.forms import ModelForm
from models import Event, Band
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class DanceForm(forms.Form):
    name = forms.CharField(max_length=100)

class EventForm(ModelForm):
    class Meta:
        model = Event
        exclude = ['dance']

class EventForm(forms.Form):
    date = forms.DateField()
    band = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'autocomplete':'off'}))
    caller = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'autocomplete':'off'}))

class BandForm(ModelForm):
    class Meta:
        model = Band

class UserForm(forms.Form):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    email = forms.EmailField()

class UserCreationWithNameForm(UserCreationForm):
    first_name = forms.CharField(max_length=30,required=False)
    last_name = forms.CharField(max_length=30,required=False)

main/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from datetime import date, datetime
from main.helpers import normalize_string

from google.appengine.api import users

from main.models import Dance, Band, Event, Homeship, UserProfile, FacebookLink, Attendship, Person
from main.forms import DanceForm, EventForm, BandForm, UserCreationWithNameForm, UserForm

from secrets import APP_SECRET
from google.appengine.api.urlfetch import fetch

from django.utils import simplejson as json
import settings

def index(request):

    dances = Dance.objects.all().order_by('name')
    bands = Band.objects.all().order_by('name')
    users = User.objects.select_related('attendships').all().order_by('-date_joined')[:20]

    return render_to_response('main/index.html', RequestContext(request, 
                                                 {'dances':dances,
                                                  'bands':bands,
                                                  'users':users}))

def profile(request, id):
    user = User.objects.get(pk=id)

    try:
        profile = user.get_profile()
    except UserProfile.DoesNotExist:
        profile = UserProfile(user=user)
        profile.save()

    attendships = user.attendships.order_by("date")
    for attendship in attendships:
        attendship.past = attendship.date < date.today()

    return render_to_response('main/profile.html', RequestContext(request, {'profile':profile,'attendships':attendships}))

@login_required
def home_profile(request):
    user = request.user

    try:
        profile = user.get_profile()
    except UserProfile.DoesNotExist:
        profile = UserProfile(user=user)
        profile.save()

    attendships = user.attendships.order_by("date")
    for attendship in attendships:
        attendship.past = attendship.date < date.today()

    return render_to_response('main/home_profile.html', RequestContext(request, {'profile':profile, 'attendships':attendships}))

@login_required
def profile_edit(request):
    user = request.user

    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            user.email = form.cleaned_data['email']
            user.save()

            return HttpResponseRedirect( reverse( 'main.views.home_profile' ) )
        
    else:
        form = UserForm(initial={'first_name':user.first_name,'last_name':user.last_name,'email':user.email})

    return render_to_response('main/profile_edit.html', {'form':form,'dance':dance})

def dance(request, id):
    dance = Dance.objects.get(pk=id)

    events = dance.event_set.all().order_by('date').select_related('attendships')

    if request.user.is_authenticated():
        attended_events = set([x[0] for x in Attendship.objects.filter(user=request.user).values_list('event_id')])

        for event in events:
            event.attended = event.id in attended_events

    # user's home dance?
    homeship=None
    if request.user and request.user.is_authenticated():
        try:
            homeship = Homeship.objects.get(user=request.user,dance=dance)
	except Homeship.DoesNotExist:
	    pass

    homeships = Homeship.objects.select_related('user').filter(dance=dance)

    now = date.today()

    return render_to_response('main/dance.html', RequestContext(request,{'dance':dance, 'events':events, 'homeship':homeship, 'homeships':homeships,'now':now}))

@login_required
def event_attend(request, id):
    event = Event.objects.get(pk=id)
    attendship, created = Attendship.objects.get_or_create(user=request.user, event=event, date=event.date)
    attendship.save()

    return HttpResponseRedirect( reverse( 'main.views.dance', args=(event.dance_id,)) )

@login_required
def event_unattend(request, id):
    event = Event.objects.get(pk=id)
    try:
        attendship = Attendship.objects.get(user=request.user, event=event)
        attendship.delete()
    except Attendship.DoesNotExist:
        pass

    return HttpResponseRedirect( reverse('main.views.dance', args=(event.dance_id,)) )

def band(request,id):
    band = Band.objects.get(pk=id)

    events = band.event_set.all().order_by('date')
    members = band.members.all()

    return render_to_response('main/band.html', RequestContext(request, {'band':band, 'events':events, 'members':members} ))

@login_required
def dance_add(request):
    if request.method == 'POST': # If the form has been submitted...
        form = DanceForm(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            name = form.cleaned_data['name']
            dance = Dance(name=name)
            dance.save()
            return HttpResponseRedirect('/') # Redirect after POST

    return render_to_response('main/dance_add.html', {})

def event_add(request, id):
    dance = Dance.objects.get(pk=id)

    if request.method == "POST":
        form = EventForm(request.POST)
        if form.is_valid():
            # figure out band
            band, band_created = Band.objects.get_or_create(name=form.cleaned_data['band'])
            # figure out caller
            caller, caller_created = Person.objects.get_or_create(name=form.cleaned_data['caller'])

            event = Event(date=form.cleaned_data['date'],band=band,caller=caller,dance=dance)
            event.save()
            return HttpResponseRedirect( reverse( 'main.views.dance', args=(event.dance.id,) ) )
        
    else:
        form = EventForm()

    return render_to_response('main/event_add.html', {'form':form,'dance':dance})

@login_required
def band_add(request):
    if request.method == "POST":
        form = BandForm(request.POST)
        if form.is_valid():
            band = form.instance
            band.save()
            return HttpResponseRedirect( "/" )
    else:
        form = BandForm()

    return render_to_response('main/band_add.html', {'form':form})

def signup(request):
    if request.method == 'POST': 
        form = UserCreationWithNameForm(request.POST)
        if form.is_valid(): 
                        
            user = User.objects.create_user(form.cleaned_data['username'], 
                                            "",
                                            form.cleaned_data['password1'])

            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            user.save()
            
            user = authenticate(username=form.cleaned_data['username'], 
                                password=form.cleaned_data['password1'])
            
            login( request, user )

            UserProfile(user=user).save()

            return HttpResponseRedirect('/accounts/profile/')
    else:
        form = UserCreationWithNameForm()

    return render_to_response('main/signup.html', {
        'form': form,
    })

def set_home_dance(request):
    dance = Dance.objects.get(pk=request.GET['dance'])

    homeship = Homeship.objects.get_or_create(user=request.user, dance=dance)

    return HttpResponseRedirect("/dance/%s/"%dance.id)

def unset_home_dance(request):
    dance = Dance.objects.get(pk=request.GET['dance'])

    try:
      homeship = Homeship.objects.get(user=request.user, dance=dance)
      homeship.delete()
    except Homeship.DoesNotExist:
      pass

    return HttpResponseRedirect("/dance/%s/"%dance.id)

def get_facebook_access_token(oauth_code):
    redirect_uri='http://localhost:8000/facebook_auth'

    url = "https://graph.facebook.com/oauth/access_token?client_id=%s&redirect_uri=%s&client_secret=%s&code=%s"%(settings.FACEBOOK_APP_ID,redirect_uri,APP_SECRET,oauth_code)

    return fetch( url ).content

def get_facebook_profile(access_token):
    url = "https://graph.facebook.com/me?"+access_token 

    return json.loads( fetch( url ).content )

def get_facebook_friends(access_token):
    url = "https://graph.facebook.com/me/friends?"+access_token

    return json.loads( fetch( url ).content )

def facebook_auth(request):
    oauth_code = request.GET['code']

    access_token = get_facebook_access_token(oauth_code)

    facebook_profile = get_facebook_profile( access_token )

    facebook_link = FacebookLink(oauth_code=oauth_code,
                                 access_token=access_token,
                                 account_id = facebook_profile['id'],
                                 name = facebook_profile['name'],
                                 link = facebook_profile['link'])
    facebook_link.save()

    profile = request.user.get_profile()
    profile.facebook = facebook_link
    profile.save()

    return HttpResponseRedirect( "/accounts/profile" )

def facebook_disconnect(request):
    profile = request.user.get_profile()
    profile.facebook = None
    profile.save()

    return HttpResponseRedirect( "/accounts/profile" )

def facebook_pull(request):
    profile = request.user.get_profile()
    
    facebook = profile.facebook

    if facebook is None:
        return HttpResponse("ain't got no facebook")

    return HttpResponse( str(get_facebook_friends(facebook.access_token)) )

def fixattendships(request):

    for attendship in Attendship.objects.all():
        if attendship.date is None:
            attendship.date = attendship.event.date
            attendship.save()

    return HttpResponse('success')

def fixpeople(request):
    for person in Person.objects.all():
        person.name_normalized = normalize_string(person.name)
        person.save()

    return HttpResponse('success')

def fixbands(request):

templates/main/band.html
{% extends "main/base.html" %}
{% block content %}
<h1>{{band.name}}</h1>
<h2>members</h2>
<ul>
{% for member in members %}
<li>{{ member.person.name }} ({% for instrument in member.instruments.all %}{{instrument.instrument.name}}{% if not forloop.last %}, {%endif%}{% endfor %})</li>
{% endfor %}
</ul>
<h2>events</h2>
<ul>
{% for event in events %}
<li>{{event.date}} - <a href="{% url main.views.dance event.dance.id %}">{{event.dance.name}}</a></li>
{% endfor %}
</ul>
{% endblock %}

templates/main/band_add.html
{% extends "main/base.html" %}
{% block content %}
<h1>Add Band</h1>
<form method="post">
{{ form.as_p }}
<input type="submit"/>
</form>
{% endblock %}

templates/main/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <link rel="stylesheet" href="/css/blueprint/screen.css" type="text/css" media="screen, projection">
    <link rel="stylesheet" href="/css/blueprint/print.css" type="text/css" media="print"> 
    <!--[if lt IE 8]>
      <link rel="stylesheet" href="/css/blueprint/ie.css" type="text/css" media="screen, projection">
    <![endif]-->
    <script type="text/javascript" src="/js/jquery-1.5.js"></script>
    <title>Dance Contraption</title>
    {% block scripts %}
    {% endblock %}
  </head>
  <body>
    <div class="container">
      <div style="background-color:#FFF380;padding:8px;margin-bottom:6px" id="header" class="span-24 last">
        <div class="span-18">
	  <a href="/" style="text-decoration:none"><h1 style="margin:0px">Dance Contraption</h1></a>
	</div>
	<div class="span-6 last">
          {% if user.is_authenticated %}
            you're totally logged in as <a href="{% url main.views.home_profile  %}">{{user.username}}</a> <a href="{% url django.contrib.auth.views.logout_then_login %}">logout</a>
          {% else %}
            <a href="{% url django.contrib.auth.views.login %}">login</a> <a href="/accounts/signup/">sign up</a>
          {% endif %}
        </div>
      </div>
      <div class="span-24 last">
      {% block content %}{% endblock %}
      </div>
    </div>
  </body>
</html>

templates/main/dance.html
{% extends "main/base.html" %}
{% block content %}
<h1>{{dance.name}}</h1>
{% if user.is_authenticated %}{% if homeship %}this is your home dance! <a href="{% url main.views.unset_home_dance %}?dance={{dance.id}}">unset</a>{% else %}<a href="{% url main.views.set_home_dance %}?dance={{dance.id}}">set as home dance</a>{% endif %}{% endif %}
<h2>events</h2>
<ul>
{% for event in events %}
<li>{{event.date}} - 
    {% if event.band %}
        <a href="{% url main.views.band event.band_id %}">{{event.band.name}}</a>
    {% else %}
        mystery band
    {% endif %} 
    {% if not event.attended %}
    <a href="{% url main.views.event_attend event.id %}">
        {% if event.date > now %}
            I'm going
        {% else %}
            I went
        {% endif %}
    </a>
    {% else %}
    <a href="{% url main.views.event_unattend event.id %}">
        {% if event.date > now %}
            I'm not going 
        {% else %}
            I didn't go 
        {% endif %}
    </a>
    {% endif %} - {{event.attendships.count}} dancers
</li>
{% empty %}
no events
{% endfor %}
</ul>
<a href="{% url main.views.event_add dance.id %}">add event</a>

<h2>dancers</h2>
<ul>
{% for homeship in homeships %}
<li><a href="{% url main.views.profile homeship.user.id %}">{{homeship.user}}</a></li>
{% empty %}
no one calls this their home dance...yet!
{% endfor %}
</ul>
{% endblock %}

templates/main/dance_add.html
{% extends "main/base.html" %}
{% block content %}
<h1>Add Dance</h1>
<form method=post>
name: <input type="text" name="name"/><input type="submit">
</form>
{% endblock %}

templates/main/event_add.html
{% extends "main/base.html" %}

{% block scripts %}
<script type="text/javascript">
    $(document).ready(function(){

        react_to_caller_search = function(data) {
            // blank suggestion list
            $("#caller_suggestions").html("");

            // for each suggestion
            for(i=0; i<data.matches.length;i++) {
                // create a div
                var matchdiv = $("<div>"+data.matches[i]+"</div>")
                
                // highlight on mouseover
                matchdiv.mouseenter(function(event) {
                    $(this).css('background-color','#E8E8E8');
                }).mouseleave(function(event) {
                    $(this).css('background-color','white');
                });

                // on click set form text to div text 
                matchdiv.click(function(event){
                    $("#id_caller").val($(event.currentTarget).text());
                })

                // slap this div on the end of the suggestions list
                $("#caller_suggestions").append( matchdiv );
            }
        }

        react_to_band_search = function(data) {
            // blank suggestion list
            $("#band_suggestions").html("");

            // for each suggestion
            for(i=0; i<data.matches.length;i++) {
                // create a div
                var matchdiv = $("<div>"+data.matches[i]+"</div>")
                
                // highlight on mouseover
                matchdiv.mouseenter(function(event) {
                    $(this).css('background-color','#E8E8E8');
                }).mouseleave(function(event) {
                    $(this).css('background-color','white');
                });

                // on click set form text to div text 
                matchdiv.click(function(event){
                    $("#id_band").val($(event.currentTarget).text());
                })

                // slap this div on the end of the suggestions list
                $("#band_suggestions").append( matchdiv );
            }
        }

        functionQueued = false;

        $('#id_caller').keydown(function(event) {
            if (!functionQueued) {
                window.setTimeout(function() {
                    var input_value = event.currentTarget.value;
                    $.getJSON("/person/search/json/?q="+input_value, react_to_caller_search);
                    functionQueued = false;
                }, 400, true);
                functionQueued = true;
            }
        });

        $('#id_band').keydown(function(event) {
            if (!functionQueued) {
                window.setTimeout(function() {
                    var input_value = event.currentTarget.value;
                    $.getJSON("/band/search/json/?q="+input_value, react_to_band_search);
                    functionQueued = false;
                }, 400, true);
                functionQueued = true;
            }
        });

    });
</script>
{% endblock %}

{% block content %}
<h1>{{dance.name}} - Add Event</h1>
<form method="post">
    {{ form.non_field_errors }}
    <div>
        {{ form.date.errors }}
        <label for="id_date">Date:</label>
        {{ form.date }}
    </div>
    <div>
        {{ form.band.errors }}
        <label for="id_band">Band:</label>
        {{ form.band }}
    </div>
    <div id="band_suggestions">
    </div>
    <div>
        {{ form.caller.errors }}
        <label for="id_caller">Caller:</label>
        {{ form.caller }}
    </div>
    <div id="caller_suggestions">
    </div>
    <input type="submit"/>
</form>
{% endblock %}

templates/main/home_profile.html
{% extends "main/base.html" %}

{% block content %}
  <div>
    <h1>{{request.user.get_profile.display_name}}</h1>
  <div>
  <p>
  <a href="{% url main.views.profile_edit %}">edit profile</a>
  {% if profile.facebook %}
    connected to facebook account <a href="{{profile.facebook.link}}">{{profile.facebook.name}}</a> - <a href="{% url main.views.facebook_disconnect %}">disconnect</a>
  {% else %}
    <a href="https://www.facebook.com/dialog/oauth?client_id=192070850827451&redirect_uri=http://localhost:8000/facebook_auth&scope=publish_stream">connect to facebook</a>
  {% endif %}
  </p>

  <h2>home dance</h2>
  <ul>
  {% for homeship in request.user.homeships.all %}
  <li><a href="{% url main.views.dance homeship.dance.id %}">{{homeship.dance.name}}</a></li>
  {% endfor %}
  </ul>

  <h2>events</h2>
  <ul>
  {% for attendship in attendships %}
  <li {% if attendship.past %}style="color:gray"{% endif %}><a href="{% url main.views.dance attendship.event.dance_id %}">{{attendship.event.dance}}</a> on {{attendship.event.date}}</li>
  {% endfor %}
  </ul>
{% endblock %}

templates/main/index.html
{% extends "main/base.html" %}

{% block content %}
  <div>
    <h2>What is Dance Contraption?</h2>
    <p>Dance Contraption is:</p>
    <p>
        <ul>
            <li>Brand new, and pretty useless right now. Find Brandon Martin-Anderson (badhill@gmail.com) and tell him what you think!</li>
            <li>A tool for effective dance gypsying.</li>
            <li>A place to host a community history of how callers, bands, events, and dancers interacted and crossed paths, and how contra has spread and changed over time.</li>
            <li>A place to moving dance organization off of Facebook and onto a place that doesn't exist explicitly to exploit community interactions for commercial gain.</li>
        </ul>
    </p>
    <p>Also!</p>
    <p>
    <ul>
      <li>Dance Contraption is open source. <a href="https://github.com/bmander/dancecontraption">Dance Contraption github page</a>.</li>
      <li>Use github to <a href="https://github.com/bmander/dancecontraption/issues">file bugs and feature requests.</a></li>
      <li>Sam Kleinman made a contra wiki at <a href="http://contra.balanceandsing.com/">http://contra.balanceandsing.com/</a>.</li>
      <li>Don't pronounce it "dance contraception" in your head.</li>
    </ul>
    </p>
    <h2>dances</h2>
    <ul>
    {% for dance in dances %}
      <li><a href="/dance/{{dance.id}}/">{{ dance.name }}</a></li>
    {% endfor %}
    </ul>
    <div>
      <a href="/dance/add/">add dance</a>
    </div>
    <h2>bands</h2>
    <ul>
    {% for band in bands %}
      <li><a href="{% url main.views.band band.id %}">{{band.name}}</a></li>
    {% endfor %}
    {% if user.is_authenticated %}
    {% endif %}
    </ul>
    <div>
      <a href="{% url main.views.band_add %}">add band</a>
    </div>
    <h2>new people</h2>
    <ul>
    {% for user in users %}
    <li><a href="{% url main.views.profile user.id %}">{{user.get_profile.display_name}}</a> {{user.homeships.all.0.dance.name}} - joined {{user.date_joined|date}}</li>
    {% endfor %}
    </ul>
    <p style='padding-top:5px'>
    <a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-sa/3.0/88x31.png" /></a> 
    </p>
    <div>
{% endblock %}

templates/main/login.html
{% extends "main/base.html" %}
{% block content %}
<h1>get ready to log in</h1>
<form method="post">
<input name="username"/><br/>
<input name="password"/><br/>
<input type="submit"/>
</form>
{% endblock %}

templates/main/map.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <link rel="stylesheet" href="/css/blueprint/screen.css" type="text/css" media="screen, projection">
    <link rel="stylesheet" href="/css/blueprint/print.css" type="text/css" media="print"> 
    <!--[if lt IE 8]>
      <link rel="stylesheet" href="/css/blueprint/ie.css" type="text/css" media="screen, projection">
    <![endif]-->
    <script type="text/javascript" src="/js/polymaps.js"></script>
    <script type="text/javascript" src="/js/jquery-1.5.js"></script>
    <script type="text/javascript">
      $(document).ready( function() {
      var po = org.polymaps;

      var map = po.map()
          .container(document.getElementById("map").appendChild(po.svg("svg")))
	  .add(po.interact())
	  .add(po.hash());

      map.add(po.image()
          .url(po.url("http://{S}tile.cloudmade.com"
          + "/55719c07a98a425497aa2e0fbec1f335"
          + "/998/256/{Z}/{X}/{Y}.png")
          .hosts(["a.", "b.", "c.", ""])));

      map.add(po.compass()
          .pan("none"));
      })
    </script>
    <title>Dance Contraption</title>
  </head>
  <body>
    <div class="container">
      <div class="span-24">
        <h1>Dance Contraption</h1>
      </div>
      <div class="span-24" id="map" height=200></div> 
    </div>
  </body>
</html>

templates/main/profile.html
{% extends "main/base.html" %}

{% block content %}
  <div>
    <h1>{{profile.display_name}}</h1>
  <div>
  <p>
  <h2>home dance</h2>
  {% if profile.user.homeships.all %}
  <ul>
  {% for homeship in profile.user.homeships.all %}
  <li><a href="{% url main.views.dance homeship.dance.id %}">{{homeship.dance.name}}</a></li>
  {% endfor %}
  </ul>
  {% else %}
  <p>no home dance</a>
  {% endif %}
  <h2>events</h2>
  {% if profile.user.attendships.all %}
  <ul>
  {% for attendship in attendships %}
  <li {% if attendship.past %}style="color:gray"{% endif %}><a href="{% url main.views.dance attendship.event.dance_id %}">{{attendship.event.dance}}</a> on {{attendship.event.date}}</li>
  {% endfor %}
  {% else %}
  <p>not attending anything</p>
  {% endif %}
  </ul>
{% endblock %}